const KEY="memorize-free-v1";
const defaults={texts:[],groups:[],settings:{theme:"dark",voice:true},sessions:[],streak:0,lastPractice:null};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(defaults);
let view="home", practiceState=null;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(s){let t=$("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function words(t){return t.trim()?t.trim().split(/\s+/).length:0}
function progress(t){return Math.max(0,Math.min(100,t.progress||0))}
function due(t){return !t.nextReview||new Date(t.nextReview)<=new Date()}
function fmtDate(d){return d?new Date(d).toLocaleDateString(): "Not scheduled"}
function render(){document.querySelectorAll(".nav[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));let s=$("#globalSearch")?.value?.toLowerCase()||""; if(view==="home")home(s);if(view==="texts")texts(s);if(view==="practice")practiceHome();if(view==="stats")stats();if(view==="groups")groups();if(view==="settings")settings()}
function showView(v){view=v;render()}
function home(s=""){let all=db.texts.filter(t=>(t.title+" "+t.content).toLowerCase().includes(s));let dueN=all.filter(due).length;$("#content").innerHTML=`
<div class="hero"><div><div class="eyebrow">Your memory workspace</div><h1>Welcome back.</h1><p>Build recall through short, focused practice sessions.</p></div><button class="btn primary" onclick="openEditor()">＋ Add memorization</button></div>
<div class="grid"><div class="card"><div class="muted">Texts</div><div class="stat">${db.texts.length}</div><div class="small muted">Unlimited</div></div><div class="card"><div class="muted">Due today</div><div class="stat">${dueN}</div><div class="small muted">Ready for review</div></div><div class="card"><div class="muted">Practice streak</div><div class="stat">${db.streak} day${db.streak===1?"":"s"}</div><div class="small muted">Keep it going</div></div></div>
<div class="sectionhead"><h2>Continue learning</h2><button class="btn" onclick="showView('texts')">View all</button></div>
<div class="grid">${all.slice(0,6).map(textCard).join("")||`<div class="empty" style="grid-column:1/-1"><h3>No memorization texts yet</h3><p>Add your first passage, verse, speech, script, poem, or anything you want to remember.</p><button class="btn primary" onclick="openEditor()">Create one</button></div>`}</div>`}
function textCard(t){return `<div class="card textcard"><div class="muted small">${esc(t.language||"English")} · ${words(t.content)} words</div><h3>${esc(t.title)}</h3><div class="preview">${esc(t.content)}</div><div class="progress"><i style="width:${progress(t)}%"></i></div><div class="small muted" style="margin-top:6px">${progress(t)}% mastered · ${due(t)?"Due now":"Next: "+fmtDate(t.nextReview)}</div><div class="actions"><button class="btn primary" onclick="startPractice('${t.id}')">Practice</button><button class="btn" onclick="openEditor('${t.id}')">Edit</button></div></div>`}
function texts(s=""){let all=db.texts.filter(t=>(t.title+" "+t.content).toLowerCase().includes(s));$("#content").innerHTML=`<div class="hero"><div><div class="eyebrow">Library</div><h1>My texts</h1><p>${db.texts.length} memorization${db.texts.length===1?"":"s"} · everything is stored locally.</p></div><button class="btn primary" onclick="openEditor()">＋ New text</button></div><div class="grid">${all.map(textCard).join("")||`<div class="empty" style="grid-column:1/-1">Nothing matches your search.</div>`}</div>`}
function openEditor(id){let t=db.texts.find(x=>x.id===id)||{id:"",title:"",language:"English",content:"",goal:0,progress:0,chunkSize:40};$("#modal").classList.remove("hidden");$("#modal").innerHTML=`<div class="dialog"><h2>${id?"Edit memorization":"New memorization"}</h2><div class="row"><div class="field"><label>Title</label><input id="fTitle" value="${esc(t.title)}" placeholder="e.g. Psalm 23"></div><div class="field"><label>Language</label><select id="fLang">${["English","Spanish","French","German","Italian","Portuguese","Latin","Other"].map(x=>`<option ${x===t.language?"selected":""}>${x}</option>`).join("")}</select></div></div><div class="field"><label>Text</label><textarea id="fContent" placeholder="Paste or type the text you want to memorize…">${esc(t.content)}</textarea></div><div class="row"><div class="field"><label>Chunk size (words)</label><input id="fChunk" type="number" min="5" max="200" value="${t.chunkSize||40}"></div><div class="field"><label>Target date (optional)</label><input id="fGoal" type="date" value="${t.goal||""}"></div></div><div class="notice">No premium limits. Texts, chunks, practice modes and statistics are all available.</div><div class="modalfoot">${id?`<button class="btn danger" onclick="deleteText('${id}')">Delete</button>`:""}<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveText('${id}')">Save text</button></div></div>`}
function closeModal(){$("#modal").classList.add("hidden");$("#modal").innerHTML=""}
function saveText(id){let title=$("#fTitle").value.trim()||"Untitled";let content=$("#fContent").value.trim();if(!content)return toast("Add some text first.");let old=db.texts.find(x=>x.id===id);let t=old||{id:uid(),createdAt:new Date().toISOString(),progress:0,history:[],reviews:0};Object.assign(t,{title,language:$("#fLang").value,content,chunkSize:+$("#fChunk").value||40,goal:$("#fGoal").value});if(!old)db.texts.unshift(t);save();closeModal();toast("Saved");render()}
function deleteText(id){if(confirm("Delete this memorization and its practice history?")){db.texts=db.texts.filter(t=>t.id!==id);save();closeModal();render()}}
function startPractice(id){let t=db.texts.find(x=>x.id===id);if(!t)return;practiceState={id,mode:"reveal",index:0,shown:false,score:0,attempts:0,sessionStart:Date.now()};view="practice";renderPractice()}
const modes=[["reveal","Tap to Reveal","Hide selected words and recall them."],["first","First Letter","Replace words with their first letters."],["blank","Fill in the Blank","Recall randomly hidden words."],["scramble","Scramble","Put the words back in order."],["type","Type It","Type the missing passage yourself."],["choice","Multiple Choice","Choose the missing word."],["listen","Listen","Hear the passage with text hidden."],["speak","Speak","Recite the passage using your microphone."],["scene","Run Scene","Practice a chunk as a scene or speech."],["familiar","Familiarize","Read along and build familiarity."]];
function practiceHome(){let dueTexts=db.texts.filter(due);$("#content").innerHTML=`<div class="hero"><div><div class="eyebrow">Practice</div><h1>What do you want to review?</h1><p>Choose a text, then pick any practice mode.</p></div></div>${db.texts.length?`<div class="grid">${db.texts.map(t=>`<div class="card"><h3>${esc(t.title)}</h3><p class="muted">${progress(t)}% mastered · ${due(t)?"Due":"Scheduled "+fmtDate(t.nextReview)}</p><div class="actions"><button class="btn primary" onclick="startPractice('${t.id}')">Practice</button></div></div>`).join("")}</div>`:`<div class="empty">Create a text first.</div>`}`}
function renderPractice(){let t=db.texts.find(x=>x.id===practiceState.id);if(!t)return showView("practice");let mode=modes.find(x=>x[0]===practiceState.mode)||modes[0];let chunk=t.content.split(/\s+/);let start=Math.floor(practiceState.index/Math.max(1,t.chunkSize||40))*(t.chunkSize||40);let slice=chunk.slice(start,start+(t.chunkSize||40));let pct=Math.round((start/chunk.length)*100);$("#content").innerHTML=`<div class="practice"><div class="sectionhead"><div><div class="eyebrow">${esc(t.title)}</div><h2>${mode[1]}</h2><div class="muted">${mode[2]}</div></div><button class="btn" onclick="showView('practice')">Exit</button></div><div class="progress"><i style="width:${Math.min(100,pct)}%"></i></div><div class="practicebox" style="margin-top:18px">${practiceBody(mode[0],slice,t)}</div><div class="sectionhead"><div class="muted">Chunk ${Math.floor(start/(t.chunkSize||40))+1} · ${slice.length} words</div><button class="btn" onclick="chooseMode('${t.id}')">Change mode</button></div></div>`}
function practiceBody(mode,a,t){let plain=a.join(" ");if(mode==="reveal"){let n=Math.max(1,Math.floor(a.length*.3));let x=a.map((w,i)=>i<n?`<span class="masked" style="color:transparent;background:#2a2e38;border-radius:4px;padding:0 3px;user-select:none">${esc(w)}</span>`:esc(w)).join(" ");return `<div class="practiceText">${x}</div><div class="actions"><button class="btn primary" onclick="practiceReveal(this)">Reveal</button><button class="btn" onclick="completePractice(1)">I knew it</button><button class="btn" onclick="completePractice(0)">I missed it</button></div>`}
if(mode==="first"){return `<div class="practiceText">${a.map(w=>`<span class="letter">${esc(w[0]||"")}${"_".repeat(Math.max(1,Math.min(5,w.length-1)))}</span>`).join(" ")}</div><div class="actions"><button class="btn primary" onclick="completePractice(1)">I got it</button><button class="btn" onclick="completePractice(0)">Review again</button></div>`}
if(mode==="blank"){let i=Math.floor(a.length/2);return `<div class="practiceText">${a.map((w,j)=>j===i?`<input id="answer" class="inlineinput" autofocus placeholder="word">`:esc(w)).join(" ")}</div><div class="actions"><button class="btn primary" onclick="checkBlank('${esc(a[i]||"")}')">Check</button></div>`}
if(mode==="type"){return `<div class="field"><label>Type the chunk from memory</label><textarea id="typed" autofocus placeholder="Start typing…"></textarea></div><div class="actions"><button class="btn primary" onclick="checkTyped(${JSON.stringify(plain)})">Check</button></div>`}
if(mode==="choice"){let i=Math.floor(a.length/2),correct=a[i]||"";let opts=[correct,...a.filter((_,j)=>j!==i).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);return `<div class="practiceText">${a.slice(0,i).map(esc).join(" ")} <b>_____</b> ${a.slice(i+1).map(esc).join(" ")}</div><div class="choicegrid">${opts.map(x=>`<button class="choice" onclick="completePractice(${x===correct?1:0})">${esc(x)}</button>`).join("")}</div>`}
if(mode==="scramble"){let s=[...a].sort(()=>Math.random()-.5);return `<div class="practiceText muted">${s.map(esc).join(" · ")}</div><p class="muted">Say the original passage aloud, then check yourself.</p><div class="actions"><button class="btn primary" onclick="completePractice(1)">Correct</button><button class="btn" onclick="completePractice(0)">Needs work</button></div>`}
if(mode==="listen"){return `<div class="practiceText" style="filter:blur(10px);user-select:none">${esc(plain)}</div><div class="actions"><button class="btn primary" onclick="speak(${JSON.stringify(plain)})">▶ Play</button><button class="btn" onclick="completePractice(1)">Done</button></div>`}
if(mode==="speak"){return `<div class="notice">Press Start and recite the chunk. Speech recognition works in supported browsers.</div><div id="speechResult" class="practiceText muted" style="margin-top:18px">Your words will appear here.</div><div class="actions"><button class="btn primary" onclick="startSpeech(${JSON.stringify(plain)})">🎙 Start</button><button class="btn" onclick="completePractice(1)">I completed it</button></div>`}
if(mode==="scene"){return `<div class="practiceText">${esc(plain)}</div><p class="muted">Run the chunk as if you were performing it. Add emotion, pacing, and gestures.</p><div class="actions"><button class="btn primary" onclick="speak(${JSON.stringify(plain)})">▶ Read aloud</button><button class="btn" onclick="completePractice(1)">Complete scene</button></div>`}
return `<div class="practiceText">${esc(plain)}</div><div class="actions"><button class="btn primary" onclick="speak(${JSON.stringify(plain)})">▶ Listen</button><button class="btn" onclick="completePractice(1)">Familiar now</button></div>`}
function chooseMode(id){let t=db.texts.find(x=>x.id===id);$("#modal").classList.remove("hidden");$("#modal").innerHTML=`<div class="dialog"><h2>Practice mode</h2><div class="grid2">${modes.map(m=>`<button class="card choice" onclick="practiceState.mode='${m[0]}';closeModal();renderPractice()"><b>${m[1]}</b><div class="small muted">${m[2]}</div></button>`).join("")}</div></div>`}
function practiceReveal(btn){btn.previousElementSibling.querySelectorAll(".masked").forEach(x=>{x.style.color="";x.style.background="transparent"});btn.remove()}
function checkBlank(correct){let v=$("#answer").value.trim().toLowerCase();completePractice(v===correct.toLowerCase()?1:0)}
function checkTyped(expected){let got=$("#typed").value.trim().toLowerCase().replace(/[^\w\s]/g,"");let exp=expected.toLowerCase().replace(/[^\w\s]/g,"");let a=got.split(/\s+/),b=exp.split(/\s+/),hit=a.filter((x,i)=>x===b[i]).length;completePractice(hit/Math.max(1,b.length))}
function completePractice(score){let t=db.texts.find(x=>x.id===practiceState.id);let s=Math.max(0,Math.min(1,Number(score)||0));practiceState.attempts++;practiceState.score+=s;t.reviews=(t.reviews||0)+1;t.history=t.history||[];t.history.push({date:new Date().toISOString(),mode:practiceState.mode,score:s});let old=t.progress||0;t.progress=Math.round(Math.min(100,old+(s?Math.max(2,8-old*.04):0)));let days=s>=.8?([1,3,7,18,45][Math.min(4,Math.floor((t.reviews||1)-1))]||60):1;t.nextReview=new Date(Date.now()+days*864e5).toISOString();db.sessions.push({date:new Date().toISOString(),text:t.title,mode:practiceState.mode,score:s});let today=new Date().toDateString(),last=db.lastPractice?new Date(db.lastPractice).toDateString():null;if(last!==today){db.streak=last===new Date(Date.now()-864e5).toDateString()?db.streak+1:1;db.lastPractice=new Date().toISOString()}save();if((practiceState.index+(t.chunkSize||40))<words(t.content)){practiceState.index+=t.chunkSize||40;toast("Chunk completed");renderPractice()}else{toast("Text review complete!");showView("practice")}}
function speak(text){if(!("speechSynthesis"in window))return toast("Speech is not supported here.");speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.rate=.9;speechSynthesis.speak(u)}
function startSpeech(expected){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast("Speech recognition isn't supported by this browser.");let r=new SR();r.continuous=true;r.interimResults=true;r.lang="en-US";r.onresult=e=>{let out="";for(let i=e.resultIndex;i<e.results.length;i++)out+=e.results[i][0].transcript+" ";$("#speechResult").textContent=out};r.onerror=()=>toast("Microphone recognition error.");r.start();setTimeout(()=>r.stop(),20000)}
function stats(){let total=db.sessions.length,avg=total?Math.round(db.sessions.reduce((a,x)=>a+x.score,0)/total*100):0;let mastered=db.texts.filter(t=>(t.progress||0)>=80).length;$("#content").innerHTML=`<div class="hero"><div><div class="eyebrow">Insights</div><h1>Statistics</h1><p>See how your memory is improving.</p></div></div><div class="grid"><div class="card"><div class="muted">Practice sessions</div><div class="stat">${total}</div></div><div class="card"><div class="muted">Average recall</div><div class="stat">${avg}%</div></div><div class="card"><div class="muted">Mastered texts</div><div class="stat">${mastered}/${db.texts.length}</div></div></div><div class="sectionhead"><h2>Text mastery</h2></div><div class="card">${db.texts.map(t=>`<div class="barrow"><div><span>${esc(t.title)}</span><b>${progress(t)}%</b></div><div class="progress"><i style="width:${progress(t)}%"></i></div></div>`).join("")||"<div class='muted'>No data yet.</div>"}</div><div class="sectionhead"><h2>Recent sessions</h2></div><div class="card">${db.sessions.slice(-10).reverse().map(x=>`<div class="listrow"><span>${esc(x.text)} · ${esc(x.mode)}</span><b>${Math.round(x.score*100)}%</b></div>`).join("")||"<div class='muted'>Start practicing to build your history.</div>"}</div>`}
function groups(){if(!db.groups.length)db.groups=[{id:uid(),name:"My Study Group",code:uid().slice(0,6).toUpperCase(),members:1}];let g=db.groups[0];save();$("#content").innerHTML=`<div class="hero"><div><div class="eyebrow">Social</div><h1>Groups</h1><p>Organize study sessions and compare progress.</p></div><button class="btn primary" onclick="createGroup()">＋ Create group</button></div><div class="grid">${db.groups.map(g=>`<div class="card"><div class="muted small">GROUP</div><h3>${esc(g.name)}</h3><div class="kpi"><span class="muted">Invite code</span><b>${esc(g.code)}</b></div><div class="kpi" style="margin-top:12px"><span class="muted">Members</span><b>${g.members||1}</b></div><div class="actions"><button class="btn" onclick="navigator.clipboard?.writeText('${g.code}');toast('Code copied')">Copy code</button></div></div>`).join("")}</div><div class="notice" style="margin-top:18px">This offline edition keeps group data on this device. Add Firebase or another backend later if you want real multi-device synchronization.</div>`}
function createGroup(){let name=prompt("Group name");if(!name)return;db.groups.push({id:uid(),name,code:uid().slice(0,6).toUpperCase(),members:1});save();render()}
function settings(){$("#content").innerHTML=`<div class="hero"><div><div class="eyebrow">Preferences</div><h1>Settings</h1><p>Everything is unlocked and stored on this device.</p></div></div><div class="card"><div class="listrow"><div><b>Speech</b><div class="small muted">Use your browser's built-in text-to-speech.</div></div><input type="checkbox" ${db.settings.voice?"checked":""} onchange="db.settings.voice=this.checked;save()"></div><div class="listrow"><div><b>Spaced repetition</b><div class="small muted">Reviews progress through 1, 3, 7, 18, 45+ day intervals.</div></div><span class="tag">Enabled</span></div><div class="listrow"><div><b>Premium features</b><div class="small muted">There is no premium tier in this version.</div></div><span class="tag">Unlocked</span></div><div class="actions"><button class="btn" onclick="exportData()">Export all data</button><button class="btn danger" onclick="wipe()">Erase all data</button></div></div>`}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="memorize-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.texts)throw 0;db=x;save();render();toast("Backup imported")}catch{toast("Invalid backup")}};r.readAsText(f)}
function wipe(){if(confirm("Erase every text, session and group from this device?")){db=structuredClone(defaults);save();render();toast("Data erased")}}
function toggleTheme(){document.body.classList.toggle("light");localStorage.setItem("mem-theme",document.body.classList.contains("light")?"light":"dark")}
if(localStorage.getItem("mem-theme")==="light")document.body.classList.add("light");
render();